#首先python中要安装scipy和numpy两个库
from scipy.optimize import curve_fit
import numpy as np
import os
case = 2 #不要改变
#work_path文件所在位置（不包含文件名）
work_path = "E:\\work\\ester_reax\\gas\\TAE\\TAE\\" 
R = 0.008314
T = [2500]
#mol是要提取的分子化学式，可在输出文件中打开看一下
mol = ["H30C19O5"]
myk = []
#step是文件共包含多少个输出
step = 2001
step_no = [[0]*(len(T)+1) for _ in range(step)]
data_files = os.listdir(work_path)
for m in range(len(T)):
    data = open(work_path + data_files[m], 'r')
    step = []
    no = []
    content = data.readlines()
    for i in range(0,len(content),2):
        line = content[i].split()
        for j in range(len(line)):
            if line[j] == mol[case-2]:
                line = content[i+1].split()
                #40000是反应开始的lammps时间步数
                if int(line[0]) >= 40000:
                    t = (int(line[0]) - 40000)*0.1/1000
                    step.append(t)
                    no.append(float(line[j-1]))
                break
    for n in range(len(no)):
        step_no[n][0] = step[n]
        step_no[n][m+1] = no[n]
    def func(x,A,k):
        return A*np.exp(-k*x)
 
    popt, pvov = curve_fit(func,step,no)
    myk.append(popt[1])
 
def func_a(t,A,Ea):
    return A*np.exp(-Ea/(R*t))
popt1, pvov1 = curve_fit(func_a,T,myk)
 
for i in range(len(myk)):
    T[i] = 1/T[i]/R
    myk[i] = np.log(myk[i])
 
def func_b(t1,B,K):
    return B-K*t1
popt2, pvov2 = curve_fit(func_b,T,myk)
 
T_k = open(work_path + "T_k", 'w')
 
for i in range(len(T)):
    line = str(T[i]) + " " + str(myk[i]) + "\n"
    T_k.write(line)
T_k.close()
 
step_no_file = open(work_path + "step_no", 'w')
temp = len(step_no)
for i in range(len(step_no)):
    line = ""
    for j in range(len(step_no[0])):
        if step_no[i][j] != 0:
            line += str(step_no[i][j]) + " "
    line += "\n"
    step_no_file.write(line)
 
step_no_file.close()
print(popt1)
print(popt2)
————————————————
版权声明：本文为CSDN博主「慕然分子模拟」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/wohenaibaoluyao/article/details/122672202